name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Update npm
        run: |
          npm update -g
          npm --version

      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ secrets.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ secrets.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build app and image
        run: |
          npm run build
          docker build -f containers/Dockerfile -t homenitor .

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tags
        run: |
          docker tag homenitor ${{ secrets.DOCKER_ORGANISATION }}/front:$(echo ${GITHUB_SHA} | cut -c1-7)
          docker tag homenitor ${{ secrets.DOCKER_ORGANISATION }}/front:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_ORGANISATION }}/front:$(echo ${GITHUB_SHA} | cut -c1-7)
          docker push ${{ secrets.DOCKER_ORGANISATION }}/front:latest
